### ISSUE TITLE
Compile in list type generic specialization

### ISSUE THREAD

**Issue by LucianViana** [forax/civilizer#2]
My question is, when the project use "type generic" with specialization, will it be possible to test whether the value has the type specified in the list and return an error at compile time?

**Comment by forax** [comment]
Hello Lucian,
the answer is probably no, recent tests have shown that no existing codes will run if things like casts are fully enforced, see https://www.youtube.com/watch?v=JI09cs2yUgY

The current plan is to specialize i.e. propagate a runtime type *only* if it's a value type and *only* use it to enhance performance. So the limitations of erasure are here to stay.

**Comment by LucianViana** [comment]
This "type extension in binary" interests me and if you could participate in the discussion it would be an honor, because I commented to the author of the book "DOP - Data oriented programming - Yehonathan Sharvit" that there was another alternative at compile time to use DOP in Java with the "type" not being cleaned from the binary. But the DIEGO project has better potential than the solution we found which is the conversion by "getters" methods of the value in "String/Integer..." at runtime and would be replaced by the extension of the "type" by the "value class" at runtime as you said and it would be more performant and organized, even if it might not have the "specialized generic type" at compile time due to the cleaning done of the type in the binary.

The discussion about DOP in Java has [started:](https://coderanch.com/t/740716/engineering/Data-Oriented-programming-applicable-Java)

Discussion on using DOP with prototype [DIEGO](https://coderanch.com/t/40/740716/engineering/Data-Oriented-programming-applicable-Java#3575826):

[Book](https://www.amazon.com/Data-Oriented-Programming-Unlearning-Yehonathan-Sharvit/dp/1617298573):
Thanks

**Comment by LucianViana** [comment]
Amazing work and thank you very much, I will do the tests and post the results if possible.
